# Input/output configuration
input_dir: /bigdata/shared/TrackML/train_all
output_dir: ../data/hitgraphs_med_002
n_files: 8192

# Graph building configuration
selection:
    pt_min: 0.5 # GeV
    phi_slope_max: 0.0006
    z0_max: 150
    n_phi_sections: 4
    n_eta_sections: 2
    eta_range: [-5, 5]
